name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@v3
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'build: apply changes'
  tests:
    name: Tests
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - id: email
        uses: ./
        with:
          module: 'internet'
          method: 'email'
      - uses: actalog/expect@v1
        with:
          type: 'regex'
          value: ${{ steps.email.outputs.value }}
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
